### ISSUE TITLE
Initial Setup

### ISSUE THREAD

**Issue by jgibbs1188** [rgs1690/JoesHotDogs#2]
- [x] Add front end folder to repo
- [x] gitignore
- [x] create project
- [x] everyone clone project locally
- [x] create ERD
- [x] create mockup

**Comment by rgs1690** [comment]
https://dbdiagram.io/d/624f718ad043196e3918fb7c

**Comment by rgs1690** [comment]
https://www.figma.com/proto/az8dS4y6035hQManTGod2m/Joe's-Hot-Dogs?node-id=8%3A38&starting-point-node-id=5%3A7&scaling=scale-down
